IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BONUS_SERVICES')
BEGIN
    CREATE TABLE [dbo].[BONUS_SERVICES] (
        [ID] INT IDENTITY(1,1) PRIMARY KEY,
        [NAME] NVARCHAR(255) NOT NULL,
        [DESCRIPTION] NVARCHAR(1000) NULL,
        [PRICE] DECIMAL(18, 2) NOT NULL,
        [HOST_ID] INT NOT NULL,
        [SERVICE_ID] INT NULL,
        [CREATED_AT] DATETIME NULL DEFAULT GETDATE(),
        [UPDATED_AT] DATETIME NULL DEFAULT GETDATE(),
        [IMAGE] NVARCHAR(MAX) NULL,
        [STATUS] NVARCHAR(50) NULL DEFAULT 'active',
        CONSTRAINT [FK_BONUS_SERVICES_HOST] FOREIGN KEY ([HOST_ID]) REFERENCES [dbo].[ACCOUNTS]([ID]),
        CONSTRAINT [FK_BONUS_SERVICES_SERVICE] FOREIGN KEY ([SERVICE_ID]) REFERENCES [dbo].[SERVICE]([ID]) ON DELETE SET NULL
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[BOOKINGS]') AND name = 'BONUS_SERVICE_ID')
BEGIN
    ALTER TABLE [dbo].[BOOKINGS]
    ADD [BONUS_SERVICE_ID] INT NULL,
    CONSTRAINT [FK_BOOKINGS_BONUS_SERVICE] FOREIGN KEY ([BONUS_SERVICE_ID]) REFERENCES [dbo].[BONUS_SERVICES]([ID]) ON DELETE SET NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_BONUS_SERVICES_HOST_ID')
    CREATE INDEX [IX_BONUS_SERVICES_HOST_ID] ON [dbo].[BONUS_SERVICES]([HOST_ID]);
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_BOOKINGS_BONUS_SERVICE_ID')
    CREATE INDEX [IX_BOOKINGS_BONUS_SERVICE_ID] ON [dbo].[BOOKINGS]([BONUS_SERVICE_ID]);
GO
