// Mock data cho tất cả các API endpoints
// Dữ liệu này sẽ được sử dụng thay cho backend API

import type { ServiceComboResponse } from '~/types/serviceCombo'

// Mock Users với các role khác nhau
// Role: 1 = admin, 2 = host, 3 = agency, 4 = tourist
export const mockUsers = [
  {
    Id: 1,
    Email: 'admin@esce.com',
    Name: 'Quản trị viên',
    Phone: '0123456789',
    Gender: 'male',
    Dob: '1985-01-01T00:00:00',
    Address: '123 Đường ABC, Quận 1, TP.HCM',
    Avatar: '/img/logo_esce.png',
    Role: 1, // admin
    RoleName: 'admin',
    CreatedAt: '2024-01-01T00:00:00',
    UpdatedAt: '2024-01-01T00:00:00',
  },
  {
    Id: 2,
    Email: 'host@esce.com',
    Name: 'Nguyễn Văn Host',
    Phone: '0987654321',
    Gender: 'male',
    Dob: '1990-03-15T00:00:00',
    Address: '456 Đường XYZ, Quận 2, TP.HCM',
    Avatar: '/img/logo_esce.png',
    Role: 2, // host
    RoleName: 'host',
    CreatedAt: '2024-01-02T00:00:00',
    UpdatedAt: '2024-01-02T00:00:00',
  },
  {
    Id: 3,
    Email: 'agency@esce.com',
    Name: 'Công ty Du lịch ABC',
    Phone: '0912345678',
    Gender: '',
    Dob: null,
    Address: '789 Đường DEF, Quận 3, TP.HCM',
    Avatar: '/img/logo_esce.png',
    Role: 3, // agency
    RoleName: 'agency',
    CreatedAt: '2024-01-03T00:00:00',
    UpdatedAt: '2024-01-03T00:00:00',
  },
  {
    Id: 4,
    Email: 'tourist@esce.com',
    Name: 'Trần Thị Tourist',
    Phone: '0923456789',
    Gender: 'female',
    Dob: '1995-05-20T00:00:00',
    Address: '321 Đường GHI, Quận 4, TP.HCM',
    Avatar: '/img/logo_esce.png',
    Role: 4, // tourist
    RoleName: 'tourist',
    CreatedAt: '2024-01-04T00:00:00',
    UpdatedAt: '2024-01-04T00:00:00',
  },
  {
    Id: 5,
    Email: 'level0@esce.com',
    Name: 'Nguyễn Văn Mới',
    Phone: '0934567890',
    Gender: 'male',
    Dob: '2000-01-01T00:00:00',
    Address: '999 Đường Test, Quận Test, TP.HCM',
    Avatar: '/img/logo_esce.png',
    Role: 4, // tourist
    RoleName: 'tourist',
    MembershipTier: 'none', // Level 0 - chưa có gói thành viên
    CreatedAt: '2024-01-05T00:00:00',
    UpdatedAt: '2024-01-05T00:00:00',
  },
]

// Mock ServiceCombos
export const mockServiceCombos: ServiceComboResponse[] = [
  {
    Id: 1,
    Name: 'Tour Bà Nà Hills',
    Address: 'Bà Nà Hills, Đà Nẵng',
    Description: 'Khám phá Bà Nà Hills với cáp treo dài nhất thế giới, tham quan các điểm du lịch nổi tiếng.',
    Price: 1500000,
    AvailableSlots: 50,
    Image: '/img/banahills.jpg',
    Status: 'open',
    CancellationPolicy: 'Hủy trước 24h được hoàn 100%',
    CreatedAt: '2024-01-01T00:00:00',
    UpdatedAt: '2024-01-01T00:00:00',
    HostId: 2, // Host user (ID 2)
  },
  {
    Id: 2,
    Name: 'Tour Cù Lao Chàm',
    Address: 'Cù Lao Chàm, Hội An',
    Description: 'Tham quan đảo Cù Lao Chàm, lặn biển ngắm san hô, thưởng thức hải sản tươi sống.',
    Price: 800000,
    AvailableSlots: 30,
    Image: '/img/culaocham.jpg',
    Status: 'open',
    CancellationPolicy: 'Hủy trước 48h được hoàn 100%',
    CreatedAt: '2024-01-02T00:00:00',
    UpdatedAt: '2024-01-02T00:00:00',
    HostId: 2, // Host user (ID 2)
  },
  {
    Id: 3,
    Name: 'Tour Bảo Tàng Chăm',
    Address: 'Bảo Tàng Chăm, Đà Nẵng',
    Description: 'Tham quan bảo tàng với bộ sưu tập nghệ thuật Chăm độc đáo.',
    Price: 500000,
    AvailableSlots: 100,
    Image: '/img/baotangcham.jpg',
    Status: 'open',
    CancellationPolicy: 'Hủy trước 12h được hoàn 100%',
    CreatedAt: '2024-01-03T00:00:00',
    UpdatedAt: '2024-01-03T00:00:00',
    HostId: 2, // Host user (ID 2)
  },
  {
    Id: 4,
    Name: 'Tour Làng Gốm Thanh Hà',
    Address: 'Làng Gốm Thanh Hà, Hội An',
    Description: 'Trải nghiệm làm gốm truyền thống tại làng gốm nổi tiếng.',
    Price: 300000,
    AvailableSlots: 40,
    Image: '/img/langgom.jpg',
    Status: 'open',
    CancellationPolicy: 'Hủy trước 12h được hoàn 100%',
    CreatedAt: '2024-01-04T00:00:00',
    UpdatedAt: '2024-01-04T00:00:00',
    HostId: 2, // Host user (ID 2)
  },
  {
    Id: 5,
    Name: 'Tour Sơn Trà',
    Address: 'Bán Đảo Sơn Trà, Đà Nẵng',
    Description: 'Khám phá bán đảo Sơn Trà, ngắm cảnh đẹp và tìm hiểu về động vật hoang dã.',
    Price: 1200000,
    AvailableSlots: 25,
    Image: '/img/sontra.jpg',
    Status: 'open',
    CancellationPolicy: 'Hủy trước 24h được hoàn 100%',
    CreatedAt: '2024-01-05T00:00:00',
    UpdatedAt: '2024-01-05T00:00:00',
    HostId: 2, // Host user (ID 2)
  },
  {
    Id: 6,
    Name: 'Tour Bãi Biển Mỹ Khê',
    Address: 'Bãi Biển Mỹ Khê, Đà Nẵng',
    Description: 'Thư giãn tại bãi biển đẹp nhất Đà Nẵng, tắm biển và thưởng thức hải sản.',
    Price: 600000,
    AvailableSlots: 60,
    Image: '/img/mykhe.jpg',
    Status: 'open',
    CancellationPolicy: 'Hủy trước 12h được hoàn 100%',
    CreatedAt: '2024-01-06T00:00:00',
    UpdatedAt: '2024-01-06T00:00:00',
    HostId: 2, // Host user (ID 2)
  },
]

// Mock Bookings (của tourist user - ID 4)
export const mockBookings = [
  {
    Id: 1,
    UserId: 4, // Tourist user
    ServiceComboId: 1,
    Quantity: 2,
    TotalAmount: 3000000,
    Status: 'confirmed',
    BookingDate: '2024-12-01T08:00:00',
    Notes: 'Cần hướng dẫn viên tiếng Anh',
    CreatedAt: '2024-11-25T10:00:00',
    UpdatedAt: '2024-11-25T10:00:00',
    ServiceCombo: mockServiceCombos[0],
  },
  {
    Id: 2,
    UserId: 4, // Tourist user
    ServiceComboId: 2,
    Quantity: 1,
    TotalAmount: 800000,
    Status: 'pending',
    BookingDate: '2024-12-05T09:00:00',
    Notes: '',
    CreatedAt: '2024-11-26T14:00:00',
    UpdatedAt: '2024-11-26T14:00:00',
    ServiceCombo: mockServiceCombos[1],
  },
]

// Mock Reviews (của tourist user - ID 4)
export const mockReviews = [
  {
    Id: 1,
    UserId: 4, // Tourist user
    ServiceComboId: 1,
    BookingId: 1,
    Rating: 5,
    Comment: 'Tour rất tuyệt vời! Cảnh đẹp, hướng dẫn viên nhiệt tình.',
    CreatedAt: '2024-11-26T10:00:00',
    UpdatedAt: '2024-11-26T10:00:00',
    User: mockUsers[3], // Tourist user
  },
  {
    Id: 2,
    UserId: 4, // Tourist user
    ServiceComboId: 1,
    BookingId: null,
    Rating: 4,
    Comment: 'Tour tốt, giá cả hợp lý. Chỉ có điều hơi đông người.',
    CreatedAt: '2024-11-27T15:00:00',
    UpdatedAt: '2024-11-27T15:00:00',
    User: mockUsers[3], // Tourist user
  },
  {
    Id: 3,
    UserId: 4, // Tourist user
    ServiceComboId: 2,
    BookingId: 2,
    Rating: 5,
    Comment: 'Đảo đẹp, nước trong xanh. Rất đáng để trải nghiệm!',
    CreatedAt: '2024-11-28T09:00:00',
    UpdatedAt: '2024-11-28T09:00:00',
    User: mockUsers[3], // Tourist user
  },
]

// Mock Posts - Diễn đàn du lịch
export const mockPosts = [
  {
    PostId: 1,
    Id: 1,
    UserId: 4, // Tourist user
    Title: 'Kinh nghiệm du lịch Bà Nà Hills - Hướng dẫn chi tiết',
    ArticleTitle: 'Kinh nghiệm du lịch Bà Nà Hills - Hướng dẫn chi tiết',
    Content: 'Mình vừa đi Bà Nà Hills tuần trước và muốn chia sẻ một số kinh nghiệm cho các bạn:\n\n1. Nên đi sớm vào buổi sáng để tránh đông đúc\n2. Mua vé combo sẽ tiết kiệm hơn\n3. Đừng quên mang theo áo khoác vì trên đỉnh khá lạnh\n4. Cáp treo là trải nghiệm tuyệt vời nhất, đừng bỏ lỡ!\n\nMọi người có câu hỏi gì cứ hỏi mình nhé!',
    PostContent: 'Mình vừa đi Bà Nà Hills tuần trước và muốn chia sẻ một số kinh nghiệm cho các bạn:\n\n1. Nên đi sớm vào buổi sáng để tránh đông đúc\n2. Mua vé combo sẽ tiết kiệm hơn\n3. Đừng quên mang theo áo khoác vì trên đỉnh khá lạnh\n4. Cáp treo là trải nghiệm tuyệt vời nhất, đừng bỏ lỡ!\n\nMọi người có câu hỏi gì cứ hỏi mình nhé!',
    Image: '/img/banahills.jpg',
    Images: ['/img/banahills.jpg'],
    CreatedAt: '2024-11-20T10:00:00',
    UpdatedAt: '2024-11-20T10:00:00',
    PublicDate: '2024-11-20T10:00:00',
    Status: 'Approved', // Status cần thiết để ForumPage filter
    PosterId: '4',
    PosterName: mockUsers[3].Name,
    AuthorId: 4,
    User: mockUsers[3], // Tourist user
    Author: mockUsers[3],
    LikeCount: 45,
    CommentCount: 5, // 5 top-level comments + 3 replies
    IsLiked: false,
    IsSaved: false,
    Likes: [], // Sẽ được populate từ mockPostReactions
    Comments: [], // Sẽ được populate từ mockComments
  },
  {
    PostId: 2,
    Id: 2,
    UserId: 4, // Tourist user
    Title: 'Cù Lao Chàm - Thiên đường biển đảo không thể bỏ qua',
    ArticleTitle: 'Cù Lao Chàm - Thiên đường biển đảo không thể bỏ qua',
    Content: 'Cù Lao Chàm thực sự là một thiên đường! Nước biển trong xanh như pha lê, san hô đầy màu sắc. Mình đã lặn biển và thấy rất nhiều cá đẹp. Hải sản ở đây tươi ngon và giá cả hợp lý. Nếu bạn yêu thích biển thì đây là điểm đến không thể bỏ qua!\n\nLưu ý: Nên đặt tour trước vì mùa cao điểm rất đông.',
    PostContent: 'Cù Lao Chàm thực sự là một thiên đường! Nước biển trong xanh như pha lê, san hô đầy màu sắc. Mình đã lặn biển và thấy rất nhiều cá đẹp. Hải sản ở đây tươi ngon và giá cả hợp lý. Nếu bạn yêu thích biển thì đây là điểm đến không thể bỏ qua!\n\nLưu ý: Nên đặt tour trước vì mùa cao điểm rất đông.',
    Image: '/img/culaocham.jpg',
    Images: ['/img/culaocham.jpg'],
    CreatedAt: '2024-11-21T14:00:00',
    UpdatedAt: '2024-11-21T14:00:00',
    PublicDate: '2024-11-21T14:00:00',
    Status: 'Approved',
    PosterId: '4',
    PosterName: mockUsers[3].Name,
    AuthorId: 4,
    User: mockUsers[3], // Tourist user
    Author: mockUsers[3],
    LikeCount: 67,
    CommentCount: 3, // 3 top-level comments + replies
    IsLiked: true,
    IsSaved: false,
    Likes: [],
    Comments: [],
  },
  {
    PostId: 3,
    Id: 3,
    UserId: 4,
    Title: 'Review tour Bảo Tàng Chăm - Nơi lưu giữ văn hóa Chăm Pa',
    ArticleTitle: 'Review tour Bảo Tàng Chăm - Nơi lưu giữ văn hóa Chăm Pa',
    Content: 'Bảo Tàng Chăm là một điểm đến văn hóa rất đáng để tham quan. Bộ sưu tập nghệ thuật Chăm ở đây rất phong phú và độc đáo. Mình đã học được rất nhiều về lịch sử và văn hóa của dân tộc Chăm.\n\nGiá vé rất hợp lý, chỉ 60k/người. Nên dành khoảng 2-3 tiếng để tham quan kỹ. Có hướng dẫn viên rất nhiệt tình.',
    PostContent: 'Bảo Tàng Chăm là một điểm đến văn hóa rất đáng để tham quan. Bộ sưu tập nghệ thuật Chăm ở đây rất phong phú và độc đáo. Mình đã học được rất nhiều về lịch sử và văn hóa của dân tộc Chăm.\n\nGiá vé rất hợp lý, chỉ 60k/người. Nên dành khoảng 2-3 tiếng để tham quan kỹ. Có hướng dẫn viên rất nhiệt tình.',
    Image: '/img/baotangcham.jpg',
    Images: ['/img/baotangcham.jpg'],
    CreatedAt: '2024-11-22T09:30:00',
    UpdatedAt: '2024-11-22T09:30:00',
    PublicDate: '2024-11-22T09:30:00',
    Status: 'Approved',
    PosterId: '4',
    PosterName: mockUsers[3].Name,
    AuthorId: 4,
    User: mockUsers[3],
    Author: mockUsers[3],
    LikeCount: 32,
    CommentCount: 3, // 3 top-level comments
    IsLiked: false,
    IsSaved: true,
    Likes: [],
    Comments: [],
  },
  {
    PostId: 4,
    Id: 4,
    UserId: 4,
    Title: 'Trải nghiệm làm gốm tại Làng Gốm Thanh Hà - Hội An',
    ArticleTitle: 'Trải nghiệm làm gốm tại Làng Gốm Thanh Hà - Hội An',
    Content: 'Hôm qua mình đã thử làm gốm tại Làng Gốm Thanh Hà. Đây là một trải nghiệm rất thú vị! Được tự tay nặn đất sét thành những sản phẩm gốm, cảm giác rất đặc biệt.\n\nCác nghệ nhân ở đây rất nhiệt tình hướng dẫn. Mình đã làm được một chiếc bình nhỏ, sau khi nung sẽ được gửi về nhà. Giá cả cũng rất hợp lý, khoảng 150k cho một sản phẩm.\n\nNếu bạn đến Hội An, đừng bỏ qua trải nghiệm này nhé!',
    PostContent: 'Hôm qua mình đã thử làm gốm tại Làng Gốm Thanh Hà. Đây là một trải nghiệm rất thú vị! Được tự tay nặn đất sét thành những sản phẩm gốm, cảm giác rất đặc biệt.\n\nCác nghệ nhân ở đây rất nhiệt tình hướng dẫn. Mình đã làm được một chiếc bình nhỏ, sau khi nung sẽ được gửi về nhà. Giá cả cũng rất hợp lý, khoảng 150k cho một sản phẩm.\n\nNếu bạn đến Hội An, đừng bỏ qua trải nghiệm này nhé!',
    Image: '/img/langgom.jpg',
    Images: ['/img/langgom.jpg'],
    CreatedAt: '2024-11-23T15:20:00',
    UpdatedAt: '2024-11-23T15:20:00',
    PublicDate: '2024-11-23T15:20:00',
    Status: 'Approved',
    PosterId: '4',
    PosterName: mockUsers[3].Name,
    AuthorId: 4,
    User: mockUsers[3],
    Author: mockUsers[3],
    LikeCount: 56,
    CommentCount: 3, // 3 top-level comments + 1 reply
    IsLiked: true,
    IsSaved: false,
    Likes: [],
    Comments: [],
  },
  {
    PostId: 5,
    Id: 5,
    UserId: 4,
    Title: 'Khám phá Bán Đảo Sơn Trà - Nơi gặp gỡ của thiên nhiên hoang dã',
    ArticleTitle: 'Khám phá Bán Đảo Sơn Trà - Nơi gặp gỡ của thiên nhiên hoang dã',
    Content: 'Sơn Trà là một điểm đến tuyệt vời cho những ai yêu thiên nhiên. Mình đã đi trekking trên đảo và gặp được rất nhiều động vật hoang dã, đặc biệt là vooc chà vá chân nâu - loài linh trưởng quý hiếm.\n\nCảnh quan trên đảo rất đẹp, có nhiều điểm ngắm cảnh lý tưởng. Nên đi vào buổi sáng sớm để ngắm bình minh, hoặc chiều tối để ngắm hoàng hôn.\n\nLưu ý: Nên mang theo nước và đồ ăn nhẹ, đi giày thể thao thoải mái.',
    PostContent: 'Sơn Trà là một điểm đến tuyệt vời cho những ai yêu thiên nhiên. Mình đã đi trekking trên đảo và gặp được rất nhiều động vật hoang dã, đặc biệt là vooc chà vá chân nâu - loài linh trưởng quý hiếm.\n\nCảnh quan trên đảo rất đẹp, có nhiều điểm ngắm cảnh lý tưởng. Nên đi vào buổi sáng sớm để ngắm bình minh, hoặc chiều tối để ngắm hoàng hôn.\n\nLưu ý: Nên mang theo nước và đồ ăn nhẹ, đi giày thể thao thoải mái.',
    Image: '/img/sontra.jpg',
    Images: ['/img/sontra.jpg'],
    CreatedAt: '2024-11-24T08:00:00',
    UpdatedAt: '2024-11-24T08:00:00',
    PublicDate: '2024-11-24T08:00:00',
    Status: 'Approved',
    PosterId: '4',
    PosterName: mockUsers[3].Name,
    AuthorId: 4,
    User: mockUsers[3],
    Author: mockUsers[3],
    LikeCount: 89,
    CommentCount: 3, // 3 top-level comments + 1 reply
    IsLiked: false,
    IsSaved: true,
    Likes: [],
    Comments: [],
  },
  {
    PostId: 6,
    Id: 6,
    UserId: 4,
    Title: 'Bãi Biển Mỹ Khê - Bãi biển đẹp nhất Đà Nẵng',
    ArticleTitle: 'Bãi Biển Mỹ Khê - Bãi biển đẹp nhất Đà Nẵng',
    Content: 'Mỹ Khê thực sự xứng đáng với danh hiệu một trong những bãi biển đẹp nhất thế giới! Cát trắng mịn, nước biển trong xanh, sóng vừa phải rất thích hợp để tắm biển.\n\nMình đã dành cả một ngày ở đây, tắm biển, nằm phơi nắng và thưởng thức hải sản tươi ngon tại các nhà hàng ven biển. Giá cả cũng rất hợp lý.\n\nNên đi vào buổi sáng hoặc chiều để tránh nắng gắt. Nhớ mang theo kem chống nắng nhé!',
    PostContent: 'Mỹ Khê thực sự xứng đáng với danh hiệu một trong những bãi biển đẹp nhất thế giới! Cát trắng mịn, nước biển trong xanh, sóng vừa phải rất thích hợp để tắm biển.\n\nMình đã dành cả một ngày ở đây, tắm biển, nằm phơi nắng và thưởng thức hải sản tươi ngon tại các nhà hàng ven biển. Giá cả cũng rất hợp lý.\n\nNên đi vào buổi sáng hoặc chiều để tránh nắng gắt. Nhớ mang theo kem chống nắng nhé!',
    Image: '/img/mykhe.jpg',
    Images: ['/img/mykhe.jpg'],
    CreatedAt: '2024-11-25T11:30:00',
    UpdatedAt: '2024-11-25T11:30:00',
    PublicDate: '2024-11-25T11:30:00',
    Status: 'Approved',
    PosterId: '4',
    PosterName: mockUsers[3].Name,
    AuthorId: 4,
    User: mockUsers[3],
    Author: mockUsers[3],
    LikeCount: 78,
    CommentCount: 3, // 3 top-level comments + 1 reply
    IsLiked: true,
    IsSaved: false,
    Likes: [],
    Comments: [],
  },
  {
    PostId: 7,
    Id: 7,
    UserId: 4,
    Title: 'Tips du lịch Đà Nẵng - Hội An tiết kiệm cho sinh viên',
    ArticleTitle: 'Tips du lịch Đà Nẵng - Hội An tiết kiệm cho sinh viên',
    Content: 'Là một sinh viên, mình đã tìm ra cách du lịch Đà Nẵng - Hội An với ngân sách hạn chế:\n\n1. Đặt phòng homestay thay vì khách sạn (tiết kiệm 50%)\n2. Ăn ở quán vỉa hè, chợ địa phương (ngon và rẻ)\n3. Đi xe máy thuê thay vì taxi (chỉ 100k/ngày)\n4. Mua vé combo tour để được giảm giá\n5. Đi vào mùa thấp điểm (tháng 9-11)\n\nVới 2 triệu, mình đã đi được 3 ngày 2 đêm rất vui vẻ!',
    PostContent: 'Là một sinh viên, mình đã tìm ra cách du lịch Đà Nẵng - Hội An với ngân sách hạn chế:\n\n1. Đặt phòng homestay thay vì khách sạn (tiết kiệm 50%)\n2. Ăn ở quán vỉa hè, chợ địa phương (ngon và rẻ)\n3. Đi xe máy thuê thay vì taxi (chỉ 100k/ngày)\n4. Mua vé combo tour để được giảm giá\n5. Đi vào mùa thấp điểm (tháng 9-11)\n\nVới 2 triệu, mình đã đi được 3 ngày 2 đêm rất vui vẻ!',
    Image: '/img/songhan.jpg',
    Images: ['/img/songhan.jpg'],
    CreatedAt: '2024-11-26T16:00:00',
    UpdatedAt: '2024-11-26T16:00:00',
    PublicDate: '2024-11-26T16:00:00',
    Status: 'Approved',
    PosterId: '4',
    PosterName: mockUsers[3].Name,
    AuthorId: 4,
    User: mockUsers[3],
    Author: mockUsers[3],
    LikeCount: 124,
    CommentCount: 4, // 4 top-level comments + 1 reply
    IsLiked: false,
    IsSaved: true,
    Likes: [],
    Comments: [],
  },
  {
    PostId: 8,
    Id: 8,
    UserId: 4,
    Title: 'Ẩm thực Đà Nẵng - Top 10 món ăn không thể bỏ qua',
    ArticleTitle: 'Ẩm thực Đà Nẵng - Top 10 món ăn không thể bỏ qua',
    Content: 'Sau chuyến đi Đà Nẵng, mình đã tổng hợp top 10 món ăn ngon nhất:\n\n1. Bánh xèo - giòn tan, thơm ngon\n2. Mì Quảng - đặc sản không thể bỏ qua\n3. Bún chả cá - tươi ngon, giá rẻ\n4. Bánh tráng cuốn thịt heo - đặc biệt\n5. Chè - nhiều loại, mát lạnh\n6. Bánh bèo - món ăn vặt yêu thích\n7. Nem nướng - thơm lừng\n8. Bánh canh chả cá - nóng hổi\n9. Gỏi cá Nam Ô - tươi sống\n10. Bánh mì Phượng - nổi tiếng Hội An\n\nMọi người đã thử món nào chưa?',
    PostContent: 'Sau chuyến đi Đà Nẵng, mình đã tổng hợp top 10 món ăn ngon nhất:\n\n1. Bánh xèo - giòn tan, thơm ngon\n2. Mì Quảng - đặc sản không thể bỏ qua\n3. Bún chả cá - tươi ngon, giá rẻ\n4. Bánh tráng cuốn thịt heo - đặc biệt\n5. Chè - nhiều loại, mát lạnh\n6. Bánh bèo - món ăn vặt yêu thích\n7. Nem nướng - thơm lừng\n8. Bánh canh chả cá - nóng hổi\n9. Gỏi cá Nam Ô - tươi sống\n10. Bánh mì Phượng - nổi tiếng Hội An\n\nMọi người đã thử món nào chưa?',
    Image: '/img/nongHoiAn.jpg',
    Images: ['/img/nongHoiAn.jpg'],
    CreatedAt: '2024-11-27T13:45:00',
    UpdatedAt: '2024-11-27T13:45:00',
    PublicDate: '2024-11-27T13:45:00',
    Status: 'Approved',
    PosterId: '4',
    PosterName: mockUsers[3].Name,
    AuthorId: 4,
    User: mockUsers[3],
    Author: mockUsers[3],
    LikeCount: 156,
    CommentCount: 4, // 4 top-level comments + 2 replies
    IsLiked: true,
    IsSaved: true,
    Likes: [],
    Comments: [],
  },
]

// Mock Comments - Bình luận trên các bài post
export const mockComments = [
  // ========== POST 1 - Bà Nà Hills ==========
  {
    CommentId: 1,
    PostId: 1,
    UserId: 4, // Tourist user
    ParentCommentId: null,
    Content: 'Cảm ơn bạn đã chia sẻ! Mình cũng đang định đi Bà Nà Hills cuối tuần này.',
    CreatedAt: '2024-11-20T11:00:00',
    UpdatedAt: '2024-11-20T11:00:00',
    User: mockUsers[3],
    ReactionsCount: 5,
    ReactionCounts: { like: 3, love: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 2,
    PostId: 1,
    UserId: 2, // Host user
    ParentCommentId: null,
    Content: 'Rất hữu ích! Mình sẽ note lại những tips này.',
    CreatedAt: '2024-11-20T12:00:00',
    UpdatedAt: '2024-11-20T12:00:00',
    User: mockUsers[1],
    ReactionsCount: 3,
    ReactionCounts: { like: 2, haha: 1 },
    CurrentUserReaction: 'like',
    Image: null,
  },
  {
    CommentId: 3,
    PostId: 1,
    UserId: 4, // Tourist user (user hiện tại - để test edit/delete)
    ParentCommentId: null,
    Content: 'Mình đi rồi, đúng là đẹp lắm! Cáp treo view tuyệt vời.',
    CreatedAt: '2024-11-20T14:30:00',
    UpdatedAt: '2024-11-20T14:30:00',
    User: mockUsers[3],
    ReactionsCount: 8,
    ReactionCounts: { like: 5, love: 2, wow: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 4,
    PostId: 1,
    UserId: 3, // Agency user
    ParentCommentId: null,
    Content: 'Bài viết rất chi tiết! Mình đã lưu lại để tham khảo cho tour sắp tới.',
    CreatedAt: '2024-11-20T15:00:00',
    UpdatedAt: '2024-11-20T15:00:00',
    User: mockUsers[2],
    ReactionsCount: 4,
    ReactionCounts: { like: 3, love: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 5,
    PostId: 1,
    UserId: 1, // Admin user
    ParentCommentId: null,
    Content: 'Cảm ơn bạn đã chia sẻ kinh nghiệm hữu ích cho cộng đồng!',
    CreatedAt: '2024-11-20T16:00:00',
    UpdatedAt: '2024-11-20T16:00:00',
    User: mockUsers[0],
    ReactionsCount: 6,
    ReactionCounts: { like: 4, love: 2 },
    CurrentUserReaction: 'love',
    Image: null,
  },
  // Replies cho comment 1
  {
    CommentId: 11,
    PostId: 1,
    UserId: 2,
    ParentCommentId: 1,
    Content: '@Trần Thị Tourist Đúng rồi! Bạn nên đi vào buổi sáng để tránh đông.',
    CreatedAt: '2024-11-20T11:30:00',
    UpdatedAt: '2024-11-20T11:30:00',
    User: mockUsers[1],
    ReactionsCount: 2,
    ReactionCounts: { like: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 12,
    PostId: 1,
    UserId: 3,
    ParentCommentId: 1,
    Content: '@Trần Thị Tourist Mình cũng vừa đi về, view đẹp lắm! 👍',
    CreatedAt: '2024-11-20T11:45:00',
    UpdatedAt: '2024-11-20T11:45:00',
    User: mockUsers[2],
    ReactionsCount: 1,
    ReactionCounts: { like: 1 },
    CurrentUserReaction: 'like',
    Image: null,
  },
  // Reply cho comment 3 (comment của user hiện tại)
  {
    CommentId: 13,
    PostId: 1,
    UserId: 2,
    ParentCommentId: 3,
    Content: '@Trần Thị Tourist Mình cũng thấy vậy! Cáp treo là điểm nhấn của Bà Nà.',
    CreatedAt: '2024-11-20T15:00:00',
    UpdatedAt: '2024-11-20T15:00:00',
    User: mockUsers[1],
    ReactionsCount: 3,
    ReactionCounts: { like: 2, love: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // ========== POST 2 - Cù Lao Chàm ==========
  {
    CommentId: 20,
    PostId: 2,
    UserId: 4,
    ParentCommentId: null,
    Content: 'Cù Lao Chàm đẹp quá! Mình cũng muốn đi lặn biển.',
    CreatedAt: '2024-11-21T15:00:00',
    UpdatedAt: '2024-11-21T15:00:00',
    User: mockUsers[3],
    ReactionsCount: 2,
    ReactionCounts: { like: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 21,
    PostId: 2,
    UserId: 2,
    ParentCommentId: null,
    Content: 'Hải sản ở đây tươi ngon lắm, giá cũng hợp lý nữa!',
    CreatedAt: '2024-11-21T16:20:00',
    UpdatedAt: '2024-11-21T16:20:00',
    User: mockUsers[1],
    ReactionsCount: 4,
    ReactionCounts: { like: 3, love: 1 },
    CurrentUserReaction: 'like',
    Image: null,
  },
  {
    CommentId: 22,
    PostId: 2,
    UserId: 4, // User hiện tại - để test edit/delete
    ParentCommentId: null,
    Content: 'Mình đã đi lặn biển ở đây rồi, san hô đẹp lắm! Nước trong xanh như pha lê.',
    CreatedAt: '2024-11-21T17:00:00',
    UpdatedAt: '2024-11-21T17:00:00',
    User: mockUsers[3],
    ReactionsCount: 7,
    ReactionCounts: { like: 5, wow: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  // Reply cho comment 20
  {
    CommentId: 23,
    PostId: 2,
    UserId: 3,
    ParentCommentId: 20,
    Content: '@Trần Thị Tourist Bạn nên đặt tour lặn biển trước, mùa này đông lắm!',
    CreatedAt: '2024-11-21T15:30:00',
    UpdatedAt: '2024-11-21T15:30:00',
    User: mockUsers[2],
    ReactionsCount: 1,
    ReactionCounts: { like: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // ========== POST 3 - Bảo Tàng Chăm ==========
  {
    CommentId: 30,
    PostId: 3,
    UserId: 4,
    ParentCommentId: null,
    Content: 'Bảo tàng này rất đáng để tham quan, mình đã học được nhiều điều thú vị.',
    CreatedAt: '2024-11-22T10:15:00',
    UpdatedAt: '2024-11-22T10:15:00',
    User: mockUsers[3],
    ReactionsCount: 1,
    ReactionCounts: { like: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 31,
    PostId: 3,
    UserId: 2,
    ParentCommentId: null,
    Content: 'Mình cũng đã đến đây, bộ sưu tập rất ấn tượng!',
    CreatedAt: '2024-11-22T11:00:00',
    UpdatedAt: '2024-11-22T11:00:00',
    User: mockUsers[1],
    ReactionsCount: 3,
    ReactionCounts: { like: 2, love: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 32,
    PostId: 3,
    UserId: 4, // User hiện tại
    ParentCommentId: null,
    Content: 'Giá vé chỉ 60k thôi, rất hợp lý cho một bảo tàng chất lượng như vậy!',
    CreatedAt: '2024-11-22T12:00:00',
    UpdatedAt: '2024-11-22T12:00:00',
    User: mockUsers[3],
    ReactionsCount: 5,
    ReactionCounts: { like: 4, wow: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // ========== POST 4 - Làng Gốm ==========
  {
    CommentId: 40,
    PostId: 4,
    UserId: 4,
    ParentCommentId: null,
    Content: 'Làm gốm vui lắm! Mình cũng đã làm được một chiếc bình xinh xắn.',
    CreatedAt: '2024-11-23T16:00:00',
    UpdatedAt: '2024-11-23T16:00:00',
    User: mockUsers[3],
    ReactionsCount: 4,
    ReactionCounts: { like: 2, love: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 41,
    PostId: 4,
    UserId: 3,
    ParentCommentId: null,
    Content: 'Trải nghiệm này rất thú vị! Mình đã đưa khách đến đây nhiều lần.',
    CreatedAt: '2024-11-23T17:00:00',
    UpdatedAt: '2024-11-23T17:00:00',
    User: mockUsers[2],
    ReactionsCount: 6,
    ReactionCounts: { like: 4, love: 2 },
    CurrentUserReaction: 'love',
    Image: null,
  },
  {
    CommentId: 42,
    PostId: 4,
    UserId: 4, // User hiện tại
    ParentCommentId: null,
    Content: 'Mình đã làm được chiếc bình, giờ đang chờ nung và gửi về nhà. Hồi hộp quá!',
    CreatedAt: '2024-11-23T18:00:00',
    UpdatedAt: '2024-11-23T18:00:00',
    User: mockUsers[3],
    ReactionsCount: 8,
    ReactionCounts: { like: 5, love: 2, wow: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // Reply cho comment 40
  {
    CommentId: 43,
    PostId: 4,
    UserId: 2,
    ParentCommentId: 40,
    Content: '@Trần Thị Tourist Mình cũng đã làm được một cái, rất vui!',
    CreatedAt: '2024-11-23T16:30:00',
    UpdatedAt: '2024-11-23T16:30:00',
    User: mockUsers[1],
    ReactionsCount: 2,
    ReactionCounts: { like: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  // ========== POST 5 - Sơn Trà ==========
  {
    CommentId: 50,
    PostId: 5,
    UserId: 4,
    ParentCommentId: null,
    Content: 'Sơn Trà đẹp quá! Mình đã chụp được rất nhiều ảnh đẹp.',
    CreatedAt: '2024-11-24T09:30:00',
    UpdatedAt: '2024-11-24T09:30:00',
    User: mockUsers[3],
    ReactionsCount: 3,
    ReactionCounts: { like: 2, wow: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 51,
    PostId: 5,
    UserId: 2,
    ParentCommentId: null,
    Content: 'Mình đã gặp vooc chà vá chân nâu ở đây, rất đáng yêu!',
    CreatedAt: '2024-11-24T10:00:00',
    UpdatedAt: '2024-11-24T10:00:00',
    User: mockUsers[1],
    ReactionsCount: 5,
    ReactionCounts: { like: 3, love: 2 },
    CurrentUserReaction: 'like',
    Image: null,
  },
  {
    CommentId: 52,
    PostId: 5,
    UserId: 4, // User hiện tại
    ParentCommentId: null,
    Content: 'View hoàng hôn trên đảo tuyệt đẹp! Mình đã quay được video rất đẹp.',
    CreatedAt: '2024-11-24T11:00:00',
    UpdatedAt: '2024-11-24T11:00:00',
    User: mockUsers[3],
    ReactionsCount: 9,
    ReactionCounts: { like: 6, love: 2, wow: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // Reply cho comment 50
  {
    CommentId: 53,
    PostId: 5,
    UserId: 3,
    ParentCommentId: 50,
    Content: '@Trần Thị Tourist Mình cũng chụp được nhiều ảnh đẹp lắm!',
    CreatedAt: '2024-11-24T10:00:00',
    UpdatedAt: '2024-11-24T10:00:00',
    User: mockUsers[2],
    ReactionsCount: 1,
    ReactionCounts: { like: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // ========== POST 6 - Mỹ Khê ==========
  {
    CommentId: 60,
    PostId: 6,
    UserId: 4,
    ParentCommentId: null,
    Content: 'Mỹ Khê là bãi biển đẹp nhất mình từng đến!',
    CreatedAt: '2024-11-25T12:00:00',
    UpdatedAt: '2024-11-25T12:00:00',
    User: mockUsers[3],
    ReactionsCount: 6,
    ReactionCounts: { like: 4, love: 2 },
    CurrentUserReaction: 'love',
    Image: null,
  },
  {
    CommentId: 61,
    PostId: 6,
    UserId: 2,
    ParentCommentId: null,
    Content: 'Cát trắng mịn, nước trong xanh, thật sự là thiên đường!',
    CreatedAt: '2024-11-25T13:00:00',
    UpdatedAt: '2024-11-25T13:00:00',
    User: mockUsers[1],
    ReactionsCount: 7,
    ReactionCounts: { like: 5, love: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 62,
    PostId: 6,
    UserId: 4, // User hiện tại
    ParentCommentId: null,
    Content: 'Mình đã dành cả ngày ở đây, tắm biển và ăn hải sản. Tuyệt vời!',
    CreatedAt: '2024-11-25T14:00:00',
    UpdatedAt: '2024-11-25T14:00:00',
    User: mockUsers[3],
    ReactionsCount: 4,
    ReactionCounts: { like: 3, haha: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // Reply cho comment 60
  {
    CommentId: 63,
    PostId: 6,
    UserId: 3,
    ParentCommentId: 60,
    Content: '@Trần Thị Tourist Đúng rồi! Mỹ Khê xứng đáng với danh hiệu bãi biển đẹp nhất thế giới!',
    CreatedAt: '2024-11-25T12:30:00',
    UpdatedAt: '2024-11-25T12:30:00',
    User: mockUsers[2],
    ReactionsCount: 3,
    ReactionCounts: { like: 2, love: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // ========== POST 7 - Tips tiết kiệm ==========
  {
    CommentId: 70,
    PostId: 7,
    UserId: 4,
    ParentCommentId: null,
    Content: 'Cảm ơn bạn đã chia sẻ tips tiết kiệm! Mình cũng là sinh viên nên rất cần.',
    CreatedAt: '2024-11-26T17:00:00',
    UpdatedAt: '2024-11-26T17:00:00',
    User: mockUsers[3],
    ReactionsCount: 2,
    ReactionCounts: { like: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 71,
    PostId: 7,
    UserId: 2,
    ParentCommentId: null,
    Content: 'Tips rất hữu ích! Mình sẽ áp dụng cho chuyến đi sắp tới.',
    CreatedAt: '2024-11-26T18:00:00',
    UpdatedAt: '2024-11-26T18:00:00',
    User: mockUsers[1],
    ReactionsCount: 5,
    ReactionCounts: { like: 4, love: 1 },
    CurrentUserReaction: 'like',
    Image: null,
  },
  {
    CommentId: 72,
    PostId: 7,
    UserId: 4, // User hiện tại
    ParentCommentId: null,
    Content: 'Với 2 triệu mà đi được 3 ngày 2 đêm, quá hợp lý! Mình sẽ thử áp dụng.',
    CreatedAt: '2024-11-26T19:00:00',
    UpdatedAt: '2024-11-26T19:00:00',
    User: mockUsers[3],
    ReactionsCount: 8,
    ReactionCounts: { like: 6, wow: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 73,
    PostId: 7,
    UserId: 3,
    ParentCommentId: null,
    Content: 'Bài viết rất thực tế! Cảm ơn bạn đã chia sẻ.',
    CreatedAt: '2024-11-26T20:00:00',
    UpdatedAt: '2024-11-26T20:00:00',
    User: mockUsers[2],
    ReactionsCount: 3,
    ReactionCounts: { like: 2, love: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // Reply cho comment 70
  {
    CommentId: 74,
    PostId: 7,
    UserId: 1,
    ParentCommentId: 70,
    Content: '@Trần Thị Tourist Chúc bạn có chuyến đi vui vẻ và tiết kiệm!',
    CreatedAt: '2024-11-26T17:30:00',
    UpdatedAt: '2024-11-26T17:30:00',
    User: mockUsers[0],
    ReactionsCount: 2,
    ReactionCounts: { like: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  // ========== POST 8 - Ẩm thực Đà Nẵng ==========
  {
    CommentId: 80,
    PostId: 8,
    UserId: 4,
    ParentCommentId: null,
    Content: 'Mình đã thử hết 10 món rồi, đều ngon cả! Đặc biệt là mì Quảng.',
    CreatedAt: '2024-11-27T14:30:00',
    UpdatedAt: '2024-11-27T14:30:00',
    User: mockUsers[3],
    ReactionsCount: 7,
    ReactionCounts: { like: 5, haha: 2 },
    CurrentUserReaction: 'haha',
    Image: null,
  },
  {
    CommentId: 81,
    PostId: 8,
    UserId: 2,
    ParentCommentId: null,
    Content: 'Bánh xèo và mì Quảng là 2 món mình thích nhất!',
    CreatedAt: '2024-11-27T15:00:00',
    UpdatedAt: '2024-11-27T15:00:00',
    User: mockUsers[1],
    ReactionsCount: 6,
    ReactionCounts: { like: 4, love: 2 },
    CurrentUserReaction: 'love',
    Image: null,
  },
  {
    CommentId: 82,
    PostId: 8,
    UserId: 4, // User hiện tại
    ParentCommentId: null,
    Content: 'Mình đặc biệt thích bánh tráng cuốn thịt heo, ăn hoài không chán!',
    CreatedAt: '2024-11-27T15:30:00',
    UpdatedAt: '2024-11-27T15:30:00',
    User: mockUsers[3],
    ReactionsCount: 5,
    ReactionCounts: { like: 3, haha: 2 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 83,
    PostId: 8,
    UserId: 3,
    ParentCommentId: null,
    Content: 'Bún chả cá là món ăn sáng yêu thích của mình!',
    CreatedAt: '2024-11-27T16:00:00',
    UpdatedAt: '2024-11-27T16:00:00',
    User: mockUsers[2],
    ReactionsCount: 4,
    ReactionCounts: { like: 3, love: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  // Reply cho comment 80
  {
    CommentId: 84,
    PostId: 8,
    UserId: 1,
    ParentCommentId: 80,
    Content: '@Trần Thị Tourist Mì Quảng là đặc sản không thể bỏ qua!',
    CreatedAt: '2024-11-27T15:00:00',
    UpdatedAt: '2024-11-27T15:00:00',
    User: mockUsers[0],
    ReactionsCount: 3,
    ReactionCounts: { like: 2, love: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
  {
    CommentId: 85,
    PostId: 8,
    UserId: 2,
    ParentCommentId: 80,
    Content: '@Trần Thị Tourist Mình cũng thích mì Quảng nhất! 😋',
    CreatedAt: '2024-11-27T15:15:00',
    UpdatedAt: '2024-11-27T15:15:00',
    User: mockUsers[1],
    ReactionsCount: 2,
    ReactionCounts: { like: 1, haha: 1 },
    CurrentUserReaction: null,
    Image: null,
  },
]

// Mock News - Tin tức du lịch
export const mockNews = [
  {
    Id: 1,
    id: 1,
    Title: 'Khám phá Đà Nẵng - Thành phố đáng sống nhất Việt Nam',
    title: 'Khám phá Đà Nẵng - Thành phố đáng sống nhất Việt Nam',
    Content: 'Đà Nẵng được bình chọn là thành phố đáng sống nhất Việt Nam với nhiều điểm du lịch hấp dẫn. Thành phố này sở hữu những bãi biển đẹp nhất thế giới, ẩm thực phong phú và con người thân thiện. Đà Nẵng đang trở thành điểm đến lý tưởng cho du khách trong và ngoài nước.\n\nVới hệ thống cơ sở hạ tầng hiện đại, giao thông thuận tiện và nhiều dịch vụ du lịch chất lượng, Đà Nẵng hứa hẹn sẽ là điểm đến không thể bỏ qua trong hành trình khám phá Việt Nam của bạn.',
    content: 'Đà Nẵng được bình chọn là thành phố đáng sống nhất Việt Nam với nhiều điểm du lịch hấp dẫn. Thành phố này sở hữu những bãi biển đẹp nhất thế giới, ẩm thực phong phú và con người thân thiện. Đà Nẵng đang trở thành điểm đến lý tưởng cho du khách trong và ngoài nước.\n\nVới hệ thống cơ sở hạ tầng hiện đại, giao thông thuận tiện và nhiều dịch vụ du lịch chất lượng, Đà Nẵng hứa hẹn sẽ là điểm đến không thể bỏ qua trong hành trình khám phá Việt Nam của bạn.',
    summary: 'Đà Nẵng - Thành phố đáng sống nhất Việt Nam với bãi biển đẹp, ẩm thực phong phú và con người thân thiện.',
    Image: '/img/songhan.jpg',
    image: '/img/songhan.jpg',
    CreatedAt: '2024-11-15T10:00:00',
    createdAt: '2024-11-15T10:00:00',
    UpdatedAt: '2024-11-15T10:00:00',
    updatedAt: '2024-11-15T10:00:00',
    Author: 'Admin',
    author: 'Admin',
    status: 'published',
    views: 1250,
  },
  {
    Id: 2,
    id: 2,
    Title: 'Hướng dẫn du lịch Hội An - Phố cổ đẹp nhất thế giới',
    title: 'Hướng dẫn du lịch Hội An - Phố cổ đẹp nhất thế giới',
    Content: 'Hội An là một trong những phố cổ đẹp nhất thế giới với kiến trúc độc đáo kết hợp giữa văn hóa Việt Nam, Trung Hoa và Nhật Bản. Phố cổ Hội An được UNESCO công nhận là Di sản Văn hóa Thế giới vào năm 1999.\n\nĐến Hội An, bạn sẽ được chiêm ngưỡng những ngôi nhà cổ hàng trăm năm tuổi, những chiếc đèn lồng rực rỡ sắc màu và thưởng thức những món ăn đặc sản nổi tiếng. Đặc biệt, vào đêm rằm hàng tháng, phố cổ sẽ tắt đèn điện và thắp sáng bằng đèn lồng, tạo nên một không gian lãng mạn tuyệt đẹp.',
    content: 'Hội An là một trong những phố cổ đẹp nhất thế giới với kiến trúc độc đáo kết hợp giữa văn hóa Việt Nam, Trung Hoa và Nhật Bản. Phố cổ Hội An được UNESCO công nhận là Di sản Văn hóa Thế giới vào năm 1999.\n\nĐến Hội An, bạn sẽ được chiêm ngưỡng những ngôi nhà cổ hàng trăm năm tuổi, những chiếc đèn lồng rực rỡ sắc màu và thưởng thức những món ăn đặc sản nổi tiếng. Đặc biệt, vào đêm rằm hàng tháng, phố cổ sẽ tắt đèn điện và thắp sáng bằng đèn lồng, tạo nên một không gian lãng mạn tuyệt đẹp.',
    summary: 'Hội An - Phố cổ đẹp nhất thế giới với kiến trúc độc đáo và văn hóa đa dạng.',
    Image: '/img/nongHoiAn.jpg',
    image: '/img/nongHoiAn.jpg',
    CreatedAt: '2024-11-16T14:00:00',
    createdAt: '2024-11-16T14:00:00',
    UpdatedAt: '2024-11-16T14:00:00',
    updatedAt: '2024-11-16T14:00:00',
    Author: 'Admin',
    author: 'Admin',
    status: 'published',
    views: 980,
  },
  {
    Id: 3,
    id: 3,
    Title: 'Bà Nà Hills - Điểm đến không thể bỏ qua khi đến Đà Nẵng',
    title: 'Bà Nà Hills - Điểm đến không thể bỏ qua khi đến Đà Nẵng',
    Content: 'Bà Nà Hills là một khu du lịch nổi tiếng tại Đà Nẵng với hệ thống cáp treo dài nhất thế giới. Nơi đây sở hữu khí hậu mát mẻ quanh năm, phù hợp cho những ai muốn trốn cái nóng oi bức của thành phố.\n\nTại Bà Nà Hills, du khách có thể tham quan các công trình kiến trúc độc đáo như Cầu Vàng nổi tiếng, các khu vui chơi giải trí và thưởng thức ẩm thực đa dạng. Đặc biệt, vào mùa hè, nhiệt độ tại đây chỉ khoảng 17-20 độ C, rất lý tưởng cho việc nghỉ dưỡng.',
    content: 'Bà Nà Hills là một khu du lịch nổi tiếng tại Đà Nẵng với hệ thống cáp treo dài nhất thế giới. Nơi đây sở hữu khí hậu mát mẻ quanh năm, phù hợp cho những ai muốn trốn cái nóng oi bức của thành phố.\n\nTại Bà Nà Hills, du khách có thể tham quan các công trình kiến trúc độc đáo như Cầu Vàng nổi tiếng, các khu vui chơi giải trí và thưởng thức ẩm thực đa dạng. Đặc biệt, vào mùa hè, nhiệt độ tại đây chỉ khoảng 17-20 độ C, rất lý tưởng cho việc nghỉ dưỡng.',
    summary: 'Bà Nà Hills - Khu du lịch nổi tiếng với cáp treo dài nhất thế giới và khí hậu mát mẻ quanh năm.',
    Image: '/img/banahills.jpg',
    image: '/img/banahills.jpg',
    CreatedAt: '2024-11-17T09:00:00',
    createdAt: '2024-11-17T09:00:00',
    UpdatedAt: '2024-11-17T09:00:00',
    updatedAt: '2024-11-17T09:00:00',
    Author: 'Admin',
    author: 'Admin',
    status: 'published',
    views: 2100,
  },
  {
    Id: 4,
    id: 4,
    Title: 'Cù Lao Chàm - Thiên đường biển đảo của miền Trung',
    title: 'Cù Lao Chàm - Thiên đường biển đảo của miền Trung',
    Content: 'Cù Lao Chàm là một quần đảo xinh đẹp nằm cách Hội An khoảng 18km về phía Đông. Nơi đây được biết đến với hệ sinh thái biển phong phú, làn nước trong xanh và những bãi biển hoang sơ tuyệt đẹp.\n\nCù Lao Chàm là điểm đến lý tưởng cho những ai yêu thích lặn biển, ngắm san hô và khám phá đời sống biển. Nơi đây cũng là nơi sinh sống của nhiều loài động vật biển quý hiếm. Du khách có thể tham gia các tour lặn biển, câu cá hoặc đơn giản là tắm biển và thưởng thức hải sản tươi ngon.',
    content: 'Cù Lao Chàm là một quần đảo xinh đẹp nằm cách Hội An khoảng 18km về phía Đông. Nơi đây được biết đến với hệ sinh thái biển phong phú, làn nước trong xanh và những bãi biển hoang sơ tuyệt đẹp.\n\nCù Lao Chàm là điểm đến lý tưởng cho những ai yêu thích lặn biển, ngắm san hô và khám phá đời sống biển. Nơi đây cũng là nơi sinh sống của nhiều loài động vật biển quý hiếm. Du khách có thể tham gia các tour lặn biển, câu cá hoặc đơn giản là tắm biển và thưởng thức hải sản tươi ngon.',
    summary: 'Cù Lao Chàm - Thiên đường biển đảo với hệ sinh thái phong phú và làn nước trong xanh.',
    Image: '/img/culaocham.jpg',
    image: '/img/culaocham.jpg',
    CreatedAt: '2024-11-18T11:30:00',
    createdAt: '2024-11-18T11:30:00',
    UpdatedAt: '2024-11-18T11:30:00',
    updatedAt: '2024-11-18T11:30:00',
    Author: 'Admin',
    author: 'Admin',
    status: 'published',
    views: 1650,
  },
  {
    Id: 5,
    id: 5,
    Title: 'Lễ hội đèn lồng Hội An - Sự kiện văn hóa độc đáo',
    title: 'Lễ hội đèn lồng Hội An - Sự kiện văn hóa độc đáo',
    Content: 'Lễ hội đèn lồng Hội An là một sự kiện văn hóa đặc sắc diễn ra vào đêm 14 âm lịch hàng tháng. Trong đêm lễ hội, toàn bộ phố cổ sẽ tắt đèn điện và thắp sáng bằng hàng nghìn chiếc đèn lồng đủ màu sắc.\n\nDu khách có thể thả đèn hoa đăng trên sông Hoài, tham gia các hoạt động văn hóa truyền thống và thưởng thức các món ăn đặc sản. Đây là một trải nghiệm văn hóa độc đáo mà bạn không thể bỏ qua khi đến Hội An.',
    content: 'Lễ hội đèn lồng Hội An là một sự kiện văn hóa đặc sắc diễn ra vào đêm 14 âm lịch hàng tháng. Trong đêm lễ hội, toàn bộ phố cổ sẽ tắt đèn điện và thắp sáng bằng hàng nghìn chiếc đèn lồng đủ màu sắc.\n\nDu khách có thể thả đèn hoa đăng trên sông Hoài, tham gia các hoạt động văn hóa truyền thống và thưởng thức các món ăn đặc sản. Đây là một trải nghiệm văn hóa độc đáo mà bạn không thể bỏ qua khi đến Hội An.',
    summary: 'Lễ hội đèn lồng Hội An - Sự kiện văn hóa độc đáo diễn ra vào đêm 14 âm lịch hàng tháng.',
    Image: '/img/nongHoiAn.jpg',
    image: '/img/nongHoiAn.jpg',
    CreatedAt: '2024-11-19T15:00:00',
    createdAt: '2024-11-19T15:00:00',
    UpdatedAt: '2024-11-19T15:00:00',
    updatedAt: '2024-11-19T15:00:00',
    Author: 'Admin',
    author: 'Admin',
    status: 'published',
    views: 890,
  },
  {
    Id: 6,
    id: 6,
    Title: 'Ẩm thực Đà Nẵng - Hành trình khám phá hương vị miền Trung',
    title: 'Ẩm thực Đà Nẵng - Hành trình khám phá hương vị miền Trung',
    Content: 'Đà Nẵng nổi tiếng với nền ẩm thực phong phú và đa dạng. Từ những món ăn đường phố giá rẻ đến những nhà hàng sang trọng, Đà Nẵng có đủ mọi thứ để thỏa mãn vị giác của du khách.\n\nMột số món ăn không thể bỏ qua khi đến Đà Nẵng: Mì Quảng, Bánh xèo, Bún chả cá, Bánh tráng cuốn thịt heo, và nhiều món ăn khác. Đặc biệt, hải sản ở Đà Nẵng rất tươi ngon và giá cả hợp lý, là lựa chọn lý tưởng cho những ai yêu thích hải sản.',
    content: 'Đà Nẵng nổi tiếng với nền ẩm thực phong phú và đa dạng. Từ những món ăn đường phố giá rẻ đến những nhà hàng sang trọng, Đà Nẵng có đủ mọi thứ để thỏa mãn vị giác của du khách.\n\nMột số món ăn không thể bỏ qua khi đến Đà Nẵng: Mì Quảng, Bánh xèo, Bún chả cá, Bánh tráng cuốn thịt heo, và nhiều món ăn khác. Đặc biệt, hải sản ở Đà Nẵng rất tươi ngon và giá cả hợp lý, là lựa chọn lý tưởng cho những ai yêu thích hải sản.',
    summary: 'Khám phá nền ẩm thực phong phú của Đà Nẵng với những món ăn đặc sản nổi tiếng.',
    Image: '/img/songhan.jpg',
    image: '/img/songhan.jpg',
    CreatedAt: '2024-11-20T10:00:00',
    createdAt: '2024-11-20T10:00:00',
    UpdatedAt: '2024-11-20T10:00:00',
    updatedAt: '2024-11-20T10:00:00',
    Author: 'Admin',
    author: 'Admin',
    status: 'published',
    views: 1450,
  },
  {
    Id: 7,
    id: 7,
    Title: 'Bán Đảo Sơn Trà - Nơi gặp gỡ của thiên nhiên và văn hóa',
    title: 'Bán Đảo Sơn Trà - Nơi gặp gỡ của thiên nhiên và văn hóa',
    Content: 'Bán Đảo Sơn Trà là một điểm đến thiên nhiên tuyệt vời tại Đà Nẵng. Nơi đây sở hữu hệ sinh thái rừng nhiệt đới phong phú và là nơi sinh sống của nhiều loài động vật quý hiếm, đặc biệt là vooc chà vá chân nâu.\n\nDu khách có thể tham gia các hoạt động trekking, ngắm cảnh, tham quan chùa Linh Ứng và tận hưởng không khí trong lành của rừng. Từ đỉnh Sơn Trà, bạn có thể ngắm toàn cảnh thành phố Đà Nẵng và biển xanh bao la.',
    content: 'Bán Đảo Sơn Trà là một điểm đến thiên nhiên tuyệt vời tại Đà Nẵng. Nơi đây sở hữu hệ sinh thái rừng nhiệt đới phong phú và là nơi sinh sống của nhiều loài động vật quý hiếm, đặc biệt là vooc chà vá chân nâu.\n\nDu khách có thể tham gia các hoạt động trekking, ngắm cảnh, tham quan chùa Linh Ứng và tận hưởng không khí trong lành của rừng. Từ đỉnh Sơn Trà, bạn có thể ngắm toàn cảnh thành phố Đà Nẵng và biển xanh bao la.',
    summary: 'Bán Đảo Sơn Trà - Điểm đến thiên nhiên với hệ sinh thái rừng phong phú và động vật quý hiếm.',
    Image: '/img/sontra.jpg',
    image: '/img/sontra.jpg',
    CreatedAt: '2024-11-21T08:30:00',
    createdAt: '2024-11-21T08:30:00',
    UpdatedAt: '2024-11-21T08:30:00',
    updatedAt: '2024-11-21T08:30:00',
    Author: 'Admin',
    author: 'Admin',
    status: 'published',
    views: 1120,
  },
  {
    Id: 8,
    id: 8,
    Title: 'Mùa du lịch Đà Nẵng - Hội An: Khi nào nên đi?',
    title: 'Mùa du lịch Đà Nẵng - Hội An: Khi nào nên đi?',
    Content: 'Đà Nẵng - Hội An có khí hậu nhiệt đới gió mùa với hai mùa rõ rệt: mùa khô (từ tháng 1 đến tháng 8) và mùa mưa (từ tháng 9 đến tháng 12).\n\nMùa khô là thời điểm lý tưởng nhất để du lịch với thời tiết nắng đẹp, ít mưa, phù hợp cho các hoạt động ngoài trời. Mùa mưa có thể có những cơn mưa bất chợt nhưng không ảnh hưởng nhiều đến chuyến đi.\n\nTháng 2-5 là thời điểm đẹp nhất với thời tiết mát mẻ, ít nắng gắt. Tháng 6-8 nắng nóng hơn nhưng biển rất đẹp, phù hợp cho các hoạt động tắm biển.',
    content: 'Đà Nẵng - Hội An có khí hậu nhiệt đới gió mùa với hai mùa rõ rệt: mùa khô (từ tháng 1 đến tháng 8) và mùa mưa (từ tháng 9 đến tháng 12).\n\nMùa khô là thời điểm lý tưởng nhất để du lịch với thời tiết nắng đẹp, ít mưa, phù hợp cho các hoạt động ngoài trời. Mùa mưa có thể có những cơn mưa bất chợt nhưng không ảnh hưởng nhiều đến chuyến đi.\n\nTháng 2-5 là thời điểm đẹp nhất với thời tiết mát mẻ, ít nắng gắt. Tháng 6-8 nắng nóng hơn nhưng biển rất đẹp, phù hợp cho các hoạt động tắm biển.',
    summary: 'Hướng dẫn chọn thời điểm du lịch Đà Nẵng - Hội An phù hợp nhất.',
    Image: '/img/mykhe.jpg',
    image: '/img/mykhe.jpg',
    CreatedAt: '2024-11-22T13:00:00',
    createdAt: '2024-11-22T13:00:00',
    UpdatedAt: '2024-11-22T13:00:00',
    updatedAt: '2024-11-22T13:00:00',
    Author: 'Admin',
    author: 'Admin',
    status: 'published',
    views: 1780,
  },
]

// Mock Coupons
export const mockCoupons = [
  {
    Id: 1,
    Code: 'WELCOME10',
    DiscountPercent: 10,
    DiscountAmount: null,
    MinPurchaseAmount: 1000000,
    MaxDiscountAmount: 500000,
    ServiceComboId: null, // Áp dụng cho tất cả
    ExpiryDate: '2024-12-31T23:59:59',
    IsActive: true,
  },
  {
    Id: 2,
    Code: 'SUMMER20',
    DiscountPercent: 20,
    DiscountAmount: null,
    MinPurchaseAmount: 2000000,
    MaxDiscountAmount: 1000000,
    ServiceComboId: 1,
    ExpiryDate: '2024-12-31T23:59:59',
    IsActive: true,
  },
]

// Mock PostReactions - Like reactions trên các posts
export const mockPostReactions: Record<number, number[]> = {
  1: [4], // Post 1 được like bởi tourist user (ID 4)
  2: [4], // Post 2 được like bởi tourist user (ID 4)
  3: [4], // Post 3 được like bởi tourist user (ID 4)
  4: [4], // Post 4 được like bởi tourist user (ID 4)
  5: [4], // Post 5 được like bởi tourist user (ID 4)
  6: [4], // Post 6 được like bởi tourist user (ID 4)
  7: [4], // Post 7 được like bởi tourist user (ID 4)
  8: [4], // Post 8 được like bởi tourist user (ID 4)
}

// Mock PostSaves - Posts được lưu bởi users
export const mockPostSaves: Record<number, number[]> = {
  1: [4], // Post 1 được save bởi tourist user (ID 4)
  3: [4], // Post 3 được save bởi tourist user (ID 4)
  5: [4], // Post 5 được save bởi tourist user (ID 4)
  7: [4], // Post 7 được save bởi tourist user (ID 4)
  8: [4], // Post 8 được save bởi tourist user (ID 4)
}

// Mock Complementary Services (Ưu đãi dành cho bạn) theo hạng thành viên
export type MembershipTier = 'silver' | 'gold' | 'diamond' | 'none'

export interface ComplementaryService {
  id: number
  name: string
  description: string
  icon?: string
  value: number // Giá trị dịch vụ (VNĐ)
  category: 'transport' | 'food' | 'activity' | 'guide' | 'insurance' | 'other'
}

export interface TierComplementaryServices {
  tier: MembershipTier
  tierName: string
  availableServices: ComplementaryService[]
  maxSelectable: number // Số lượng dịch vụ tối đa được chọn
}

export const mockComplementaryServices: Record<MembershipTier, TierComplementaryServices> = {
  none: {
    tier: 'none',
    tierName: 'Chưa có gói',
    availableServices: [],
    maxSelectable: 0
  },
  silver: {
    tier: 'silver',
    tierName: 'Gói Bạc',
    availableServices: [
      {
        id: 1,
        name: 'Bảo hiểm du lịch cơ bản',
        description: 'Bảo hiểm y tế và tai nạn trong suốt chuyến đi',
        category: 'insurance',
        value: 100000
      },
      {
        id: 2,
        name: 'Bữa trưa buffet',
        description: 'Bữa trưa buffet tại nhà hàng địa phương',
        category: 'food',
        value: 200000
      },
      {
        id: 3,
        name: 'Hướng dẫn viên địa phương',
        description: 'Hướng dẫn viên tiếng Việt cho nhóm nhỏ',
        category: 'guide',
        value: 300000
      },
      {
        id: 4,
        name: 'Vé tham quan bảo tàng',
        description: 'Vé vào cửa miễn phí cho các bảo tàng trong tour',
        category: 'activity',
        value: 150000
      }
    ],
    maxSelectable: 2
  },
  gold: {
    tier: 'gold',
    tierName: 'Gói Vàng',
    availableServices: [
      {
        id: 1,
        name: 'Bảo hiểm du lịch cao cấp',
        description: 'Bảo hiểm toàn diện bao gồm y tế, tai nạn và hủy chuyến',
        category: 'insurance',
        value: 200000
      },
      {
        id: 2,
        name: 'Bữa trưa và tối buffet',
        description: 'Bữa trưa và tối buffet tại nhà hàng cao cấp',
        category: 'food',
        value: 400000
      },
      {
        id: 3,
        name: 'Hướng dẫn viên chuyên nghiệp',
        description: 'Hướng dẫn viên tiếng Anh/Việt chuyên nghiệp',
        category: 'guide',
        value: 500000
      },
      {
        id: 4,
        name: 'Vé tham quan đặc biệt',
        description: 'Vé VIP vào cửa cho tất cả điểm tham quan',
        category: 'activity',
        value: 300000
      }
    ],
    maxSelectable: 2
  },
  diamond: {
    tier: 'diamond',
    tierName: 'Gói Kim Cương',
    availableServices: [
      {
        id: 1,
        name: 'Bảo hiểm du lịch VIP',
        description: 'Bảo hiểm cao cấp với bồi thường tối đa và hỗ trợ 24/7',
        category: 'insurance',
        value: 300000
      },
      {
        id: 2,
        name: 'Bữa ăn cao cấp 3 bữa',
        description: 'Bữa sáng, trưa, tối tại nhà hàng 5 sao',
        category: 'food',
        value: 600000
      },
      {
        id: 3,
        name: 'Hướng dẫn viên VIP',
        description: 'Hướng dẫn viên riêng, đa ngôn ngữ, chuyên nghiệp',
        category: 'guide',
        value: 800000
      },
      {
        id: 4,
        name: 'Vé tham quan VIP',
        description: 'Vé VIP skip-the-line cho tất cả điểm tham quan',
        category: 'activity',
        value: 500000
      },
      {
        id: 5,
        name: 'Xe limousine đưa đón',
        description: 'Xe limousine cao cấp đưa đón sân bay và trong tour',
        category: 'transport',
        value: 700000
      },
      {
        id: 6,
        name: 'Trải nghiệm độc quyền',
        description: 'Tham quan khu vực đặc biệt không mở cửa công khai',
        category: 'activity',
        value: 400000
      },
      {
        id: 7,
        name: 'Massage và spa',
        description: 'Dịch vụ massage và spa thư giãn sau tour',
        category: 'other',
        value: 350000
      },
      {
        id: 8,
        name: 'Quà lưu niệm cao cấp',
        description: 'Bộ quà lưu niệm đặc biệt từ địa phương',
        category: 'other',
        value: 200000
      }
    ],
    maxSelectable: 4
  }
}

// Mock Services (Dịch vụ đơn lẻ)
export interface ServiceResponse {
  Id: number
  Name: string
  Description?: string
  Price: number
  HostId: number
  Status?: string // Pending, Approved, Rejected, Review
  RejectComment?: string
  ReviewComments?: string
  Images?: string
  HostName?: string
  CreatedAt?: string
  UpdatedAt?: string
}

export const mockServices: ServiceResponse[] = [
  {
    Id: 1,
    Name: 'Dịch vụ hướng dẫn viên Bà Nà Hills',
    Description: 'Dịch vụ hướng dẫn viên chuyên nghiệp cho tour Bà Nà Hills. Hướng dẫn viên có kinh nghiệm, nhiệt tình, nói được tiếng Anh và tiếng Việt.',
    Price: 500000,
    HostId: 2, // Host user (ID 2)
    Status: 'Approved',
    Images: '/img/banahills.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-10T00:00:00',
    UpdatedAt: '2024-01-10T00:00:00',
  },
  {
    Id: 2,
    Name: 'Dịch vụ lặn biển Cù Lao Chàm',
    Description: 'Dịch vụ lặn biển ngắm san hô tại Cù Lao Chàm. Bao gồm thiết bị lặn, hướng dẫn viên và bảo hiểm. Phù hợp cho người mới bắt đầu.',
    Price: 600000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/culaocham.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-11T00:00:00',
    UpdatedAt: '2024-01-11T00:00:00',
  },
  {
    Id: 3,
    Name: 'Dịch vụ xe đưa đón sân bay',
    Description: 'Dịch vụ xe đưa đón từ sân bay Đà Nẵng đến khách sạn và ngược lại. Xe 4-7 chỗ, lái xe chuyên nghiệp, giá cả hợp lý.',
    Price: 300000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/songhan.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-12T00:00:00',
    UpdatedAt: '2024-01-12T00:00:00',
  },
  {
    Id: 4,
    Name: 'Dịch vụ chụp ảnh du lịch',
    Description: 'Dịch vụ chụp ảnh chuyên nghiệp tại các điểm du lịch Đà Nẵng - Hội An. Nhiếp ảnh gia có kinh nghiệm, thiết bị hiện đại.',
    Price: 800000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/nongHoiAn.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-13T00:00:00',
    UpdatedAt: '2024-01-13T00:00:00',
  },
  {
    Id: 5,
    Name: 'Dịch vụ thuê xe máy',
    Description: 'Dịch vụ thuê xe máy tự lái tại Đà Nẵng. Xe mới, bảo dưỡng định kỳ, giá cả hợp lý. Giao xe tận nơi.',
    Price: 150000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/mykhe.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-14T00:00:00',
    UpdatedAt: '2024-01-14T00:00:00',
  },
  {
    Id: 6,
    Name: 'Dịch vụ làm gốm tại Làng Gốm Thanh Hà',
    Description: 'Trải nghiệm làm gốm truyền thống tại Làng Gốm Thanh Hà. Hướng dẫn bởi nghệ nhân, sản phẩm sẽ được nung và gửi về nhà.',
    Price: 200000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/langgom.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-15T00:00:00',
    UpdatedAt: '2024-01-15T00:00:00',
  },
  {
    Id: 7,
    Name: 'Dịch vụ tham quan Bảo Tàng Chăm',
    Description: 'Dịch vụ tham quan Bảo Tàng Chăm với hướng dẫn viên chuyên nghiệp. Tìm hiểu về lịch sử và văn hóa Chăm Pa.',
    Price: 250000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/baotangcham.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-16T00:00:00',
    UpdatedAt: '2024-01-16T00:00:00',
  },
  {
    Id: 8,
    Name: 'Dịch vụ trekking Bán Đảo Sơn Trà',
    Description: 'Dịch vụ trekking khám phá Bán Đảo Sơn Trà. Hướng dẫn viên có kinh nghiệm, thiết bị an toàn, tìm hiểu về động vật hoang dã.',
    Price: 400000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/sontra.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-17T00:00:00',
    UpdatedAt: '2024-01-17T00:00:00',
  },
  {
    Id: 9,
    Name: 'Dịch vụ tắm biển Mỹ Khê',
    Description: 'Dịch vụ tắm biển tại Bãi Biển Mỹ Khê. Bao gồm ghế tắm nắng, dù che nắng, và đồ uống giải khát.',
    Price: 100000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/mykhe.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-18T00:00:00',
    UpdatedAt: '2024-01-18T00:00:00',
  },
  {
    Id: 10,
    Name: 'Dịch vụ tham quan Phố Cổ Hội An',
    Description: 'Dịch vụ tham quan Phố Cổ Hội An với hướng dẫn viên. Tìm hiểu về lịch sử, kiến trúc và văn hóa của phố cổ.',
    Price: 350000,
    HostId: 2,
    Status: 'Approved',
    Images: '/img/nongHoiAn.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-01-19T00:00:00',
    UpdatedAt: '2024-01-19T00:00:00',
  },
  {
    Id: 11,
    Name: 'Dịch vụ hướng dẫn viên tiếng Anh',
    Description: 'Dịch vụ hướng dẫn viên nói tiếng Anh chuyên nghiệp cho du khách quốc tế. Kinh nghiệm nhiều năm, kiến thức sâu rộng.',
    Price: 700000,
    HostId: 2,
    Status: 'Pending',
    Images: '/img/banahills.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-11-25T00:00:00',
    UpdatedAt: '2024-11-25T00:00:00',
  },
  {
    Id: 12,
    Name: 'Dịch vụ thuê thuyền tham quan sông Hoài',
    Description: 'Dịch vụ thuê thuyền tham quan sông Hoài tại Hội An. Ngắm cảnh phố cổ từ sông, thả đèn hoa đăng vào buổi tối.',
    Price: 450000,
    HostId: 2,
    Status: 'Review',
    ReviewComments: 'Cần bổ sung thông tin về an toàn và bảo hiểm',
    Images: '/img/nongHoiAn.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-11-20T00:00:00',
    UpdatedAt: '2024-11-24T00:00:00',
  },
  {
    Id: 13,
    Name: 'Dịch vụ không phù hợp',
    Description: 'Dịch vụ này đã bị từ chối vì không đáp ứng yêu cầu.',
    Price: 200000,
    HostId: 2,
    Status: 'Rejected',
    RejectComment: 'Dịch vụ không đáp ứng tiêu chuẩn chất lượng. Vui lòng cải thiện và gửi lại.',
    Images: '/img/songhan.jpg',
    HostName: 'Nguyễn Văn Host',
    CreatedAt: '2024-11-15T00:00:00',
    UpdatedAt: '2024-11-18T00:00:00',
  },
]

// Helper để simulate delay
export const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

